name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  unit-test:
    name: Run tests and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm install
      - run: npm run test
      - run: npm run build   
     
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}      

        
        
